### ISSUE TITLE
Some compat bounds need updating

### ISSUE THREAD

**Issue by cscherrer** [zekeriyasari/Causal.jl#57]
Hi, I noticed that some version bounds in your `Project.toml` are a little outdated. Here's a quick check with `PkgVersionHelper.jl`:

```
julia> using PkgVersionHelper

julia> upcheck()
Dict{String, Tuple{VersionNumber, VersionNumber}} with 11 entries:
  "LightGraphs"           => (v"1.3.3", v"1.3.5")
  "Sundials"              => (v"4.2.6", v"4.4.1")
  "Interpolations"        => (v"0.13.0", v"0.13.1")
  "DataStructures"        => (v"0.17.20", v"0.18.9")
  "Plots"                 => (v"1.6.12", v"1.10.6")
  "ProgressMeter"         => (v"1.4.0", v"1.5.0")
  "GraphPlot"             => (v"0.4.3", v"0.4.4")
  "FileIO"                => (v"1.4.4", v"1.6.2")
  "JLD2"                  => (v"0.3.0", v"0.4.2")
  "NLsolve"               => (v"4.4.1", v"4.5.1")
  "DifferentialEquations" => (v"6.15.0", v"6.16.0")
```

Some of these are just differences in patch versions, not affected by your `[compat]`. But a few of them seem to be held back a bit. Maybe something like `PkgVersionHelper` or `CompatHelper` (https://github.com/JuliaRegistries/CompatHelper.jl) would be useful for this?

**Comment by zekeriyasari** [comment]
Hi @cscherrer Thank you for the heads-up. I have already been using `CompatHelper`, realized that `CompatHelper` workflow was disabled in Github Actions. So I enabled it back. However, I was not aware of `PkgVersionHelper.jl`. Looks like a great tool. I updated the `[compat]`s as shown. 

https://github.com/zekeriyasari/Causal.jl/blob/a57b196289c3d4363fa7cf94c34a3116655df95b/Project.toml#L26-L39
